### ISSUE TITLE
cannot coerce class ‘"jags"’ to a data.frame

### ISSUE THREAD

**Issue by hrgene** [cbrown5/remixsiar#1]
Hi Chris, 
I got a following error while I run your example.  What is the reason of it. It would be great help for me if you have some clue. Thank you. 
> calchell(list(gulls_small_in, gulls_out))
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"jags"’ to a data.frame

Regards,
Hari

**Comment by cbrown5** [comment]
Hi Hari, I think I need to overhaul this package unfortunately, because I haven't kept up with updates to simmr and mixsiar. What do you want to do exactly? Can you post a complete example and I can show you how to calculate the information criteria.

**Comment by cbrown5** [comment]
Hi Hari. I've updated BayeSens (https://github.com/cbrown5/BayeSens) so please use that package from now on in. You might find this blog helpful: 
http://www.seascapemodels.org/rstats/2020/04/25/data-priors-in-isotope-models.html
Let me know how you go
Chris
